### PR TITLE
Fixes warnings that appeares in Xcode 9.2

### PR DESCRIPTION
**Pull request by JagCesar**
And fixes so the app uses full screen on iPhone X

Sorry about the undescriptive commits, in a bit of a hurry between flights

### CODE REVIEW

**Review by nevyn — APPROVED** [review]
LGTM!! Gonna test it before I merge, but feel free to merge t yourself if you want :)

**Comment by JagCesar** [comment]
I'm gonna wait for your approval before I merge, just in case I have misunderstood something. :)

**Comment by nevyn** [comment]
Not a single warning and builds and works great <3 <3 thanks @JagCesar!!!!

**Pull request merged**
